using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq.Expressions;
using DataManager.Campaign;
using DataManager.Shared;
using Microsoft.EntityFrameworkCore;

namespace DataManager.Infrastructure;

[Table("campaign_info")] public class CAMPAIGN_INFO {
  [Key] [DatabaseGenerated(DatabaseGeneratedOption.Identity)] public long Id { get; set; }
  public string MediaSource { get; set; }
  public string Objective { get; set; }
  public string CampaignId { get; set; }
  public string CampaignName { get; set; }
  public string CampaignStatus { get; set; }
  public string BudgetMode { get; set; }
  public double Budget { get; set; }
  [Column(TypeName = "jsonb")] public Dictionary<string, string> Options { get; set; } = [];
  public int GenRandomSeed { get; set; }
  public DateTime StartTime { get; set; }
  public DateTime? EndTime { get; set; }
  public DateTime CreateTime { get; set; }
  public DateTime? ModifyTime { get; set; }
  public DateTime CreatedAt { get; set; }
  public DateTime? UpdatedAt { get; set; }
}

public class CampaignStore(DataManagerDbContext dbContext) : ICampaignStore {
  public List<CampaignInfo> List() => GetCampaigns(x => true);

  public List<CampaignInfo> GetActiveCampaigns() => GetCampaigns(x => x.CampaignStatus == CampaignInfo.CampaignStatus.ACTIVE);

  private List<CampaignInfo> GetCampaigns(Expression<Func<CAMPAIGN_INFO, bool>> predicate) => [..dbContext.CampaignInfo
      .Where(predicate).AsNoTracking().Select(StoreMapper.FromCampaignInfo)];

  public async Task<List<CampaignInfo>> Save(List<CampaignCreate> campaignCreateList) {
    var campaigns = campaignCreateList.Select(StoreMapper.ToCampaignInfo).ToList();

    // 1. Add the list of entities to the context using AddRange
    dbContext.CampaignInfo.AddRange(campaigns);

    // 2. Save changes to the database.
    // This is the crucial step where the IDs are generated by the DB
    // and automatically assigned back to the objects in the 'campaigns' list.
    await dbContext.SaveChangesAsync();

    // 3. The IDs are now available in your original list.
    return [..campaigns.Select(StoreMapper.FromCampaignInfo)];
  }
}

public static partial class StoreMapper {
  public static CAMPAIGN_INFO ToCampaignInfo(CampaignCreate obj) {
    var createTime = TimeUtils.SystemTime.UtcDateTime;
    return new() {
      MediaSource = obj.MediaSource,
      Objective = obj.Objective,
      CampaignId = obj.CampaignId,
      CampaignName = obj.CampaignName,
      CampaignStatus = CampaignInfo.CampaignStatus.ACTIVE,
      BudgetMode = obj.BudgetMode,
      Budget = obj.Budget,
      Options = [],
      GenRandomSeed = Imc.RandomInt(1024),
      StartTime = createTime,
      EndTime = createTime.AddDays(Imc.RandomInt(1, 90)),
      CreateTime = createTime,
      CreatedAt = DateTime.UtcNow,
    };
  }

  public static CampaignInfo FromCampaignInfo(CAMPAIGN_INFO obj) => new(
    Id: obj.Id,
    MediaSource: obj.MediaSource,
    Objective: obj.Objective,
    CampaignId: obj.CampaignId,
    CampaignName: obj.CampaignName,
    Status: obj.CampaignStatus,
    BudgetMode: obj.BudgetMode,
    Budget: obj.Budget,
    Options: obj.Options,
    GenRandomSeed: obj.GenRandomSeed,
    StartTime: obj.StartTime,
    EndTime: obj.EndTime,
    CreateTime: obj.CreateTime,
    ModifyTime: obj.ModifyTime,
    CreatedAt: obj.CreatedAt,
    UpdatedAt: obj.UpdatedAt
  );
}